// External imports
import type { Metadata } from "next";
// UI imports
import { Hind_Siliguri, Poppins } from "next/font/google";
import { ThemeProvider } from "@/context/theme-context";
import "./globals.css";
// Component imports

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-hind-siliguri",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function () {
              const saved = localStorage.getItem("theme");
              if (saved) {
                document.documentElement.dataset.theme = saved;
              } else {
                const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                document.documentElement.dataset.theme = systemDark ? "dark" : "light";
              }
            })();
                `,
          }}
        />
      </head>
      <body
        className={`${hindSiliguri.variable} ${poppins.variable} antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
